using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ItauCorretora.Desafio.Models
{
    public enum TipoMovimento
    {
        Credito,
        Debito
    }

    [Table("AccountsMovements")]
    public class AccountMovement
    {
        [Key]
        public int Id { get; set; }

        public int AccountId { get; set; }

        [Required]
        [ForeignKey("Stock")]
        public int StockId { get; set; }
        public Stock Stock { get; set; } = null!;

        [Required]
        public DateTime Date { get; set; }

        [Required]
        public TipoMovimento Type { get; set; }

        [Required]
        [Column(TypeName = "decimal(18,2)")]
        public decimal Value { get; set; }

        [StringLength(200)]
        public string? Description { get; set; }

        // It may be related to Order, if the movement was generated by an order execution
        [ForeignKey("Order")]
        public int? OrderId { get; set; }
        public Order? Order { get; set; }
    }
}